const students = [
{
id: 1,
name: "ANNISHA SHAFITRI",
photo: "assets/img/ANNISA.jpg",
role: "Siswa TKJ 3",
TTL: "Bandung, 02 Juni 2008",
quote: "Kegagalan hanyalah batu loncatan menuju kesuksesan",
hobby: "Nonton Film",
FavSong:"Best Part - Daniel Caesar, H.E.R.",
ig: "annshashftri",
songTitle: "Best Part",
songArtist: "Daniel Caesar, H.E.R.",
album:"assets/img/bf3.jpeg",
music: "assets/music/annishambg.mp3",
memories: [
    "assets/img/arnes1.jpeg",
    "assets/img/arnes2.jpeg",
    "assets/img/arnes3.jpeg",
    "assets/img/arnes4.jpeg",
    "assets/img/arnes5.jpeg",
]
},
{
id: 2,
name: "ANYA ADZKYA",
photo: "assets/img/ANYA.jpg",
role: "siswa tkj 3",
TTL: "Bandung, 6 Juni 2008",
quote: "sesungguhnya bersama kesulitan ada kemudahan",
hobby: "listening to music, playing basketball ",
FavSong:"Fana merah jambu - fourtwnty",
ig: "anyazkya",
songTitle: "Fana Merah Jambu",
songArtist:"Fourtwnty",
album:"assets/img/merahjambu.jpeg",
music: "assets/music/anyambg.mp3",
memories: [

]
},
{
id: 3,
name: "APRI APQIAH",
photo: "assets/img/APRI.jpg",
role: "Siswa TKJ 3",
TTL:" Bandung, 2 mei 2008",
quote: "hiduplah seolah olah setiap momen adalah sebuah kompetisi yang ingin kamu menangkan, tapi jangan lupa untuk tertawa saat kamu kalah",
hobby: "baking, singing, drawing",
FavSong:" calla - w2e",
ig: "apiw_",
songTitle:"calla",
songArtist:"w2e",
album:"assets/img/calla.jpeg",
music:"assets/music/aprimbg.mp3",
memories:[

]
},
{
id: 4,
name: "ARNESA DWI MEIDINA",
photo: "assets/img/ARNESA.jpg",
role: "Siswa TKJ 3",
TTL:" 3 Mei 2008",
quote: "create your own time and you enjoy ",
hobby: "nonton, journaling, music listening, meditasi",
FavSong:"segelas berdua-fourtwnty, if i had magic-berbie, when i look at you-miley cyrus",
ig: "nesa.ardwina",
songTitle: "Hitam Putih",
songArtist: "Fourtwnty",
music: "assets/music/arnesmbg.mp3",
album:"assets/img/hpf.jpeg",
memories:[
    "assets/img/arnes1.jpeg",
    "assets/img/arnes2.jpeg",
    "assets/img/arnes3.jpeg",
    "assets/img/arnes4.jpeg",
    "assets/img/arnes5.jpeg",
]
},
{
id: 5,
name: "ATHORIK AHMAD FAUZAN",
photo: "assets/img/ATHORIK.jpg",
role: "Siswa TKJ 3",
TTL: "27 Januari 2008",
quote: "Don't be scared to have a some dream's, because if we have a dream, we have a goal's of life.",
hobby: "listening music, writer, swimming ",
FavSong:"Yellow-Cold Play",
ig: "znthr_",
songTitle:"Yellow",
songArtist:"Cold Play",
music:"assets/music/torikmbg.mp3",
album:"assets/img/yellow.jpeg",
memories:[
    "assets/img/torik1.jpeg",
    "assets/img/torik2.jpeg",
    "assets/img/torik3.jpeg",
    "assets/img/torik4.jpeg",
    "assets/img/torik5.jpeg",
]
},
{
id: 6,
name: "CINTYA MAULIDA",
photo: "assets/img/CINTYA.jpg",
role: "Siswa TKJ 3",
TTL:"15 Maret 2008",
quote: "kalo kemarin-kemarin banyak sedihnya semoga kedepannya banyak bahagianya, ambil baiknya buang buruknya.",
hobby: "cooking, baca novel, rebahan",
FavSong:" impossible - james arthur",
ig: "thiaazz3",
songTitle:" impossible",
songArtist:" james arthur",
music:"assets/music/cintyambg.mp3",
album:"assets/img/impossible.jpeg",
memories:[
    "assets/img/cintya1.jpeg",
    "assets/img/cintya2.jpeg",
    "assets/img/cintya3.jpeg",
    "assets/img/cintya4.jpeg",
    "assets/img/cintya5.jpeg",
]
},
{
id: 7,
name: "DINI ANDRIYANI",
photo: "assets/img/DINI.jpg",
role: "Siswa TKJ 3",
TTL:"23 januari 2009",
quote: "tanganmu hanya dua cukup untuk menggenggam doa bukan untuk memeluk seisi dunia",
hobby: "cooking,listening to music,rebahan",
FavSong:"selamat tinggal-virgoun, end of beginning - djo",
ig: "andriyanidini036",
songTitle:"selamat tinggal",
songArtist:"Virgoun",
music:"assets/music/dinimbg.mp3",
album:"",
memories:[
    "assets/img/dini1.jpeg",
    "assets/img/dini2.jpeg",
    "assets/img/dini3.jpeg",
    "assets/img/dini4.jpeg",
    "assets/img/dini5.jpeg",
]
},
{
id: 8,
name: "DISTI AVIZENIA",
photo: "assets/img/DISTI.jpg",
role: " Sekretaris TKJ 3",
TTL:"Bandung, 8 Desember 2007",
quote: " don't feel blue, it's just a bad day not a bad life then after the rain came the rainbow.",
hobby: "watching movie, hanging out, listening to music",
FavSong:"K. - Cigarettes After Sex",
ig: "__dstyal0uwvel  ",
songTitle:"K.",
songArtist:"Cigarettes After Sex",
music:"assets/music/distimbg.mp3",
album:"assets/img/k.jpeg",
memories:[
    "assets/img/disty1.jpeg",
    "assets/img/disty2.jpeg",
    "assets/img/disty3.jpeg",
    "assets/img/disty4.jpeg",
    "assets/img/disty5.jpeg",
    "assets/img/disty6.jpeg",
    "assets/img/disty7.jpeg",
    "assets/img/disty8.jpeg",
]
},
{
id: 9,
name: "DWI ALICIA NURHAKIM",
photo: "assets/img/DWI.jpg",
role: "Siswa TKJ 3",
TTL:"08 Maret 2008",
quote:" tidak semua hal harus di benarkan, biarkan mereka melihat burukmu bertumbuhlah",
hobby: "bobo",
FavSong: "Born To Die - Lana Del Ray",
ig: "dwiialisyaa",
songTitle:"Born To Die",
songArtist:"Lana Del Ray",
music:"assets/music/dwimbg.mp3",
album:"assets/img/btd.jpeg",
memories:[

]
},
{
id: 10,
name: "EVA REVITA",
photo: "assets/img/EVA.jpg",
role: "Siswa TKJ 3",
quote: "hebahst",
hobby: "okakjef",
FavSong:"",
ig: "evarevitaa",
songTitle:"",
songArtist:"",
music:"",
album:"",
memories:[

]
},
{
id: 11,
name: "FARREL THUFAILLAH HERMAWAN",
photo: "assets/img/FARREL.jpg",
role: "Siswa TKJ 3",
quote: "hdnssje",
hobby: "konshgshbd",
FavSong:"",
ig: "varrel_zzz",
songTitle:"",
songArtist:"",
music:"",
album:"",
memories:[

]
},
{
id: 12,
name: "FEBRI PUJISAPIRA",
photo: "assets/img/FEBRI.jpg",
role: "Siswa TKJ 3",
TTL:"Bandung, 15 Februari 2008",
quote: "semua akan berjuang jika memiliki sebuah tujuan.",
hobby: "Running, listening to music ",
FavSong:" rewrite the stars & sampai akhir waktu",
ig: "febripsss_",
songTitle:"rewrite the stars",
songArtist:"james arthur",
music:"assets/music/febrimbg.mp3",
album:"assets/img/rts.jpeg",
memories:[
    "assets/img/febri1.jpeg",
    "assets/img/febri2.jpeg",
    "assets/img/febri3.jpeg",
    "assets/img/febri4.jpeg",
    "assets/img/febri5.jpeg",
]
},
{
id: 13,
name: "FELIA NAFISA MARWA",
photo: "assets/img/FELIA.jpg",
role: "Siswa TKJ 3",
TTL:"Bandung, 06 Agustus 2008",
quote: "life is only as good as your mindset. a negative mind will never give you a positive life ",
hobby: "listen to music, sleep, writing",
FavSong:"pyrite - frank ocean (unreleased song), american wedding - frank ocean (unreleased song), emily’s song - daniel caesar, as i say - dream, ivory, repeat until death - novo amor",
ig: "_feeyyli",
songTitle:"Risk It All",
songArtist:"Bruno Mars",
music:"assets/music/feliambg.mp3",
album:"assets/img/bruno.jpeg",
memories:[
    "assets/img/felia1.jpeg",
    "assets/img/felia2.jpeg",
    "assets/img/felia3.jpeg",
]
},
{
id: 14,
name: "HELLEN SILA ROHMATUL HASANAH",
photo: "assets/img/default.jpg",
role: "Siswa TKJ 3",
TTL: "Bandung, 19 juli 2007",
quote: " sketching, spider livestock",
hobby: "kita hanya butuh lebih baik dari kemarin bukan lebih baik dari yang lain",
FavSong:"alive - krewella",
ig: "hellensilarh_",
songTitle:"alive",
songArtist:"krewella",
music:"assets/music/elmbg.mp3",
album:"assets/img/alive.jpeg",
memories:[

]
},
{
id: 15,
name: "KHANSA TSABITAH RAMADHANI",
photo: "assets/img/KHANSA.jpg",
role: "Siswa TKJ 3",
TTL:"07 september 2008",
quote: "waktu tidak menyembuhkan luka tetapi waktu membuat kita terbiasa dengan luka tersebut, karena sesuatu yang hilang belum tentu kita akan sembuh.",
hobby: "cooking, makeup, listening to music",
FavSong:"Mendarah - Nadin Amizah",
ig: "ach4_ca",
songTitle:"Mendarah",
songArtist:"Nadin Amizah",
music:"assets/music/khansambg.mp3",
album:"assets/img/mendarah.jpeg",
memories:[

]
},
{
id: 16,
name: "KHANSZA FELLYSA",
photo: "assets/img/KHANSZA.jpg",
role: "Siswa TKJ 3",
TTL:"01 Agustus 2008",
quote: '"Long story short, i survived" - Taylor Swift',
hobby: "badminton, drawing, listening to music, watching film/drakor",
FavSong:"Season-Wave To Earth",
ig: "__fllys",
songTitle:"Season",
songArtist:"Wave To Earth",
music:"assets/music/acambg.mp3",
album:"assets/img/season.jpeg",
memories:[
    "assets/img/acaf1.jpeg",
    "assets/img/acaf2.jpeg",
    "assets/img/acaf3.jpeg",
    "assets/img/acaf4.jpeg",
    "assets/img/acaf5.jpeg",
    "assets/img/acaf6.jpeg",
    "assets/img/acaf7.jpeg",
    "assets/img/acaf8.jpeg",
    "assets/img/acaf9.jpeg",
    "assets/img/acaf10.jpeg",
    "assets/img/acaf11.jpeg",
]
},
{
id: 17,
name: "KIN KIN PUTRI AGUSTIN",
photo: "assets/img/KIN.jpg",
role: "Siswa TKJ 3",
TTL:"17 agustus 2008",
quote: "Ketika kamu merasa ragu, ingatlah bahwa pohon paling tinggi pun pernah menjadi biji kecil yang tumbuh melalui banyak tantangan.",
hobby: "nonton",
FavSong:"that somebody - rafi sudirman",
ig: "kinkinputrii_",
songTitle:"that somebody",
songArtist:"rafi sudirman",
music:"assets/music/kinmbg.mp3",
album:"assets/img/rafi.jpeg",
memories:[
    "assets/img/kin1.jpeg",
    "assets/img/kin2.jpeg",
]
},
{
id: 18,
name: "LUTHFI RAFIF RABBANI",
photo: "assets/img/LUTHFI.jpg",
role: "Kerohanian TKJ 3",
TTL:" Bandung, 22 januari 2008",
quote: " Selalu ikuti kata hatimu. Namun, bawalah otakmu juga",
hobby: " watching film (series, movie), playing games",
FavSong:" understand - keshi",
ig: "luvlfuv_",
songTitle:"understand",
songArtist:"keshi",
music:"assets/music/lutpimbg.mp3",
album:"assets/img/keshi.jpeg",
memories:[

]
},
{
id: 19,
name: "MUHAMAD FAISAL BUSTOMI",
photo: "assets/img/FAISAL.jpg",
role: "Siswa TKJ 3",
TTL:"Bandung, 18 November 2007",
quote: " Jika keluarga mu tidak memiliki nama besar, buatlah sejarah itu atas namamu sendiri",
hobby: "Cooking, Adventure, Badminton, Basketball and Hope for someone ",
FavSong:"Multo - Cup Of Joe",
ig: "mhdfaisalbs",
songTitle:"Multo",
songArtist:"Cup Of Joe",
music:"assets/music/isalmbg.mp3",
album:"assets/img/multo.jpeg",
memories:[
   
]
},
{
id: 20,
name: "MUHAMMAD AFDHAL RAYYAN A.S.",
photo: "assets/img/AFDHAL.jpg",
role: "Siswa TKJ 3",
quote: "apa aja",
hobby: "kolasakas",
FavSong:"",
ig: "sisadol_",
songTitle:"",
songArtist:"",
music:"",
album:"",
memories:[

]
},
{
id: 21,
name: "MUHAMMAD FARDAN",
photo: "assets/img/FD.jpg",
role: "Siswa TKJ 3",
quote: "lawanlah rasa malasmu supaya kamu bisa malas-malasan.",
hobby: "melawan rasa malas",
FavSong:"",
ig: "bymfn_",
songTitle:"",
songArtist:"",
music:"",
album:"",
memories:[

]
},
{
id: 22,
name: "MUHAMMAD REIGA ALFARIZI",
photo: "assets/img/REIGA.jpg",
role: "Siswa TKJ 3",
TTL:"Aceh, 25 April 2008",
quote: "Jangan pikirin apa kata orang lain tapi pikirin gimana jadi kalcer depan orang lain",
hobby: "Fashion Styling & Playing Games",
FavSong:"",
ig: "lwkyrei.___",
songTitle:"",
songArtist:"",
music:"",
album:"",
memories:[
    "assets/img/igow5.jpeg",
    "assets/img/igow3.jpeg",
    "assets/img/igow2.jpeg",
    "assets/img/igow4.jpeg",
    "assets/img/igow1.jpeg",
    "assets/img/igow6.jpeg",
    "assets/img/igow7.jpeg",
    "assets/img/igow8.jpeg",
    "assets/img/igow9.jpeg",
]
},
{
id: 23,
name: "MUHAMMAD REZA NURDIANSYAH",
photo: "assets/img/REZA.jpg",
role: "Siswa TKJ 3",
quote: "'if life is a movie, then u're the best part!'",
TTL:"Bandung, 13 desember 2007",
hobby: " dancing, writing, also listening to music n ur voice haha",
FavSong:"losing us. - raissa anggiani",
ig: "rzzand_",
songTitle:"losing us",
songArtist:"raissa anggiani",
music:"assets/music/rezambg.mp3",
album:"assets/img/losing.jpeg",
memories:[

]
},
{
id: 24,
name: "NENG CAHYATI MAULANI",
photo: "assets/img/NENG.jpeg",
role: "Siswa TKJ 3",
TTL:"Bandung, 25 Maret 2008 ",
quote:"Aku percaya, kalau hal-hal baik akan selalu berbalas baik juga, walaupun dalam bentuk dan cara berbeda",
hobby: "listening to music, hangout",
FavSong:"bersenja gurau - raim laode",
ig: "nengcahyatiii_",
songTitle:"bersenja gurau",
songArtist:"raim laode",
music:"assets/music/nengmbg.mp3",
album:"assets/img/gurau.jpeg",
memories:[
    "assets/img/neng1.jpeg",
    "assets/img/neng2.jpeg",
    "assets/img/neng3.jpeg",
    "assets/img/neng4.jpeg",
    "assets/img/neng5.jpeg",
    "assets/img/neng6.jpeg",
]
},
{
id: 25,
name: "NENG MITA",
photo: "assets/img/MITA.jpg",
role: "Siswa TKJ 3",
TTL:" 24 Agustus 2008",
quote: "Don't stop trying for something you want..",
hobby: " Nonton C-drama, baca wattpad",
FavSong:"Taruh - Nadin Amizah",
ig: "_itsjusttaa",
songTitle:"Taruh",
songArtist:"Nadin Amizah",
music:"assets/music/mitambg.mp3",
album:"assets/img/taruh.jpeg",
memories:[
    "assets/img/mita1.jpeg",
    "assets/img/mita2.jpeg",
    "assets/img/mita3.jpeg",
    "assets/img/mita4.jpeg",
    "assets/img/mita5.jpeg",
    "assets/img/mita6.jpeg",
    "assets/img/mita7.jpeg",
]
},
{
id: 26,
name: "NOVYANTI NUR FADILAH",
photo: "assets/img/NUR.jpg",
role: "Siswa TKJ 3",
quote: "lorem ip asu",
hobby: "yowes",
FavSong:"",
ig: "wqjaiabgg___",
songTitle:"",
songArtist:"",
music:"",
album:"",
memories:[

]
},
{
id: 27,
name: "RISKA DIANA PUTRI",
photo: "assets/img/RISKA.jpg",
role: "Siswa TKJ 3",
TTL:" 27 April 2008",
quote: "keberhasilan bukanlah milik orang pintar, akan tetapi keberhasilan adalah milik mereka yang senantiasa selalu berusaha",
hobby: "cooking, listening  to music",
FavSong:" kota ini tak sama tanpamu & bersenja gurau",
ig: "jaeskaa__",
songTitle:"kota ini tak sama tanpamu",
songArtist:"nadhif Basalamah",
music:"assets/music/riskambg.mp3",
album:"assets/img/kota.jpeg",
memories:[
    "assets/img/riska1.jpeg",
    "assets/img/riska2.jpeg",
    "assets/img/riska3.jpeg",
    "assets/img/riska4.jpeg",
    "assets/img/riska5.jpeg",
    "assets/img/riska6.jpeg",
    "assets/img/riska7.jpeg",
    "assets/img/riska8.jpeg",
    "assets/img/riska9.jpeg",
    "assets/img/riska10.jpeg",
    "assets/img/riska11.jpeg",
    "assets/img/riska12.jpeg",
    "assets/img/riska13.jpeg",
    "assets/img/riska14.jpeg",
    "assets/img/riska15.jpeg",
    "assets/img/riska16.jpeg",
    "assets/img/riska17.jpeg",
    "assets/img/riska18.jpeg",
    "assets/img/riska19.jpeg",
    "assets/img/riska20.jpeg",
    "assets/img/riska21.jpeg",
    "assets/img/riska22.jpeg",
    "assets/img/riska23.jpeg",
    "assets/img/riska24.jpeg",
    "assets/img/riska25.jpeg",
    "assets/img/riska26.jpeg",
    "assets/img/riska27.jpeg",
    "assets/img/riska28.jpeg",
    "assets/img/riska29.jpeg",
    "assets/img/riska30.jpeg",
    "assets/img/riska31.jpeg",
    "assets/img/riska32.jpeg",
    "assets/img/riska33.jpeg",
    "assets/img/riska34.jpeg",
    "assets/img/riska35.jpeg",
    "assets/img/riska36.jpeg",
    "assets/img/riska37.jpeg",
    "assets/img/riska38.jpeg",
    "assets/img/riska39.jpeg",
    "assets/img/riska40.jpeg",
    "assets/img/riska41.jpeg",
]
},
{
id: 28,
name: "RIVA ADI KURNIAWAN 😎😎😜🤗😇",
photo: "assets/img/RIVA.jpg",
role: "Siswa TKJ 3",
TTL:"Bandung, 22 Januari 2008",
quote: "Now or never, sekarang atau tidak akan pernah sama sekali",
hobby: "listen to music, to learn something",
FavSong:"My Chemical Romance - Cancer",
ig: "ariva4004",
songTitle:"My Chemical Romance",
songArtist:"Cancer",
music:"assets/music/rivambg.mp3",
album:"assets/img/cancer.jpeg",
memories:[

]
},
{
id: 29,
name: "RIVIANI NURUL ALMI",
photo: "assets/img/RIVIANI.jpg",
role: "Siswa TKJ 3",
quote: "soksas",
hobby: "kopaks",
FavSong:"",
ig: "rivianinurul_",
songTitle:"",
songArtist:"",
music:"",
album:"",
memories:[

]
},
{
id: 30,
name: "SILVIA",
photo: "assets/img/SILVIA.jpg",
role: "Siswa TKJ 3",
TTL:"Bandung, 13, November 2008",
quote: "hidup itu tidak selalu adil, tapi selalu memberi pelajaran",
hobby: " listening to music",
FavSong:"bahagia lagi - piche kota",
ig: "_silvianw_",
songTitle:"bahagia lagi",
songArtist:"piche kota",
music:"assets/music/silviambg.mp3",
album:"assets/img/kota.jpeg",
memories:[
    "assets/img/silvia1.jpeg",
    "assets/img/silvia2.jpeg",
    "assets/img/silvia3.jpeg",
    "assets/img/silvia4.jpeg",
    "assets/img/silvia5.jpeg",
    "assets/img/silvia6.jpeg",
    "assets/img/silvia7.jpeg",
    "assets/img/silvia8.jpeg",
    "assets/img/silvia9.jpeg",
]
},
{
id: 31,
name: "SRI WAHYUNI",
photo: "assets/img/SRI.jpg",
role: "Siswa TKJ 3",
TTL:"Bandung 28 September 2008",
quote: "growing gently,not forcing the process",
hobby: "Traveling, Listening To Music",
FavSong:"Disarankan Dibandung - Dongker ft jason ranti",
ig: "swsriwhynii_",
songTitle:"Disarankan Dibandung",
songArtist:"Dongker ft jason ranti",
music:"assets/music/srimbg.mp3",
album:"assets/img/bandung.jpeg",
memories:[
    "assets/img/sri1.jpeg",
    "assets/img/sri2.jpeg",
    "assets/img/sri3.jpeg",
    "assets/img/sri4.jpeg",
    "assets/img/sri5.jpeg",
    "assets/img/sri6.jpeg",
    "assets/img/sri7.jpeg",
    "assets/img/sri8s.jpeg",
    "assets/img/sri9.jpeg",
]
},
{
id: 32,
name: "STEVEN FAJRI GUSTIAN",
photo: "assets/img/STEVEN.jpg",
role: "Siswa TKJ 3",
TTL: "Bandung, 20 Agustus 2008",
quote: "Tetap Bernapas",
hobby: " Jaga Warung dan Game",
FavSong:"YOASOBI - あの夢をなぞって",
ig: "ryusun_2",
songTitle:"YOASOBI",
songArtist:"あの夢をなぞっ",
music:"assets/music/stevenmbg.mp3",
album:"assets/img/yoa.jpeg",
memories:[
    "assets/img/steven1.jpeg",
    "assets/img/steven2.jpeg",
    "assets/img/steven3.jpeg",
    "assets/img/steven4.jpeg",
    "assets/img/steven5.jpeg",
]
},
{
id: 33,
name: "SUCHI EKA PUTRI RAMADHAN",
photo: "assets/img/SUCHI.jpg",
role: "Siswa TKJ 3",
TTL:"Bandung 1 September 2008",
quote: "We have hope, but the world has reality",
hobby: "Nonton drama,cooking,listening to music",
FavSong:"Runtuh - Feby Putri & Fiersa Besari",
ig: "luvxuchiii",
songTitle:"Runtuh",
songArtist:"Feby Putri & Fiersa Besari",
music:"assets/music/suchimbg.mp3",
album:"assets/img/runtuh.jpeg",
memories:[
    "assets/img/uchi1.jpeg",
    "assets/img/uchi2.jpeg",
    "assets/img/uchi3.jpeg",
    "assets/img/uchi4.jpeg",
    "assets/img/uchi5.jpeg",
    "assets/img/uchi6.jpeg",
]
},
{
id: 34,
name: "TINI NURHALIMAH",
photo: "assets/img/TINI.jpg",
role: "Siswa TKJ 3",
TTL: "Bandung, 18 Juli 2007",
quote: "cape itu wajar, nyerah itu pilihan, so keep trying not to give up until you find the point of happiness.",
hobby: "write a diary, listen to music, nonton drama",
FavSong:"Last Child-Diary Depresiku",
ig: "tinintca",
songTitle:"Last Child",
songArtist:"Diary Depresiku",
music:"assets/music/tinimbg.mp3",
album:"assets/img/diary.jpeg",
memories:[
    "assets/img/tini1.jpeg",
    "assets/img/tini2.jpeg",
    "assets/img/tini3.jpeg",
    "assets/img/tini4.jpeg",
    "assets/img/tini5.jpeg",
    "assets/img/tini5.jpeg",
    "assets/img/tini6.jpeg",
    "assets/img/tini7.jpeg",
    "assets/img/tini8.jpeg",
    "assets/img/tini9.jpeg",
    "assets/img/tini10.jpeg",
    "assets/img/tini11.jpeg",
    "assets/img/tini12.jpeg",
    "assets/img/tini13.jpeg",
    "assets/img/tini14.jpeg",
    "assets/img/tini15.jpeg",
    "assets/img/tini16.jpeg",
    "assets/img/tini17.jpeg",
    "assets/img/tini18.jpeg",
    "assets/img/tini19.jpeg",
]
},
{
id: 35,
name: "VIESCA GIANISA SAPUTRA",
photo: "assets/img/VIESCA.jpg",
role: "Bendahara 1 TKJ 3",
quote: "hidup itu singkat, buatlah manis jadi tinggal tambahin aku aja ",
hobby: " make up, listening to music",
FavSong:"",
ig: "viescagn",
songTitle:"",
songArtist:"",
music:"",
album:"",
memories:[

]
}
];
